import type { SupportedLocale } from './articleTypes';
import { normalizeLocale } from './articleLocalization';

type LabelMap = Record<SupportedLocale, Record<string, string>>;

export const articleUiLabels: LabelMap = {
  cs: {
    home: 'Euvida',
    readingTime: 'Doba čtení',
    readingTimeUnit: 'min čtení',
    checked: 'Ověřeno k',
    updated: 'Aktualizováno',
    country: 'Země',
    region: 'Region',
    featured: 'Doporučujeme',
    quickInfo: 'Rychlý přehled',
    practicalInfo: 'Praktické informace',
    prices: 'Ceník',
    access: 'Přístup & doprava',
    bookingUrl: 'Rezervace na:',
    sources: 'Zdroje a ověření',
    sourcesIntro: 'Zdroje použité pro ověření cen, provozu, pravidel a praktických informací.',
    photo: 'Foto',
    noImage: 'Obrázek není k dispozici',
    infoChecked: 'Informace ověřeny k',
    seasonNote: 'Sezónní poznámka',
    note: 'Poznámka',
    official: 'oficiální',
    indicative: 'orientační',
    usedFor: 'Použito pro',
    lines: 'Linky',
    stop: 'Zastávka',
    walk: 'Pěšky',
    parking: 'Parkování',
    roads: 'Silnice',
    destination: 'Cíl',
    yes: 'Ano',
    no: 'Ne',
    onlineOnly: 'Vstupenky pouze online',
    bookingRecommended: 'Rezervace doporučena',
    officialHours: 'Otevírací doba',
    openingHoursFallback: 'Ověř před cestou podle aktuální sezony a provozovatele.',
    nudistBeach: 'Nudistická pláž',
    waterQuality: 'Kvalita vody',
    bestTime: 'Nejlepší čas',
    avoidIfPossible: 'Kdy se raději vyhnout',
    swimmingType: 'Typ koupání',
    crowdLevel: 'Vytíženost',
    placeType: 'Typ místa',
    category: 'Kategorie',
  },
  en: {
    home: 'Euvida',
    readingTime: 'Reading time',
    readingTimeUnit: 'min read',
    checked: 'Verified on',
    updated: 'Updated',
    country: 'Country',
    region: 'Region',
    featured: 'Featured',
    quickInfo: 'Quick overview',
    practicalInfo: 'Practical information',
    prices: 'Prices',
    access: 'Access & transport',
    bookingUrl: 'Booking at:',
    sources: 'Sources and verification',
    sourcesIntro: 'Sources used to verify prices, opening details, rules, and practical information.',
    photo: 'Photo',
    noImage: 'Image not available',
    infoChecked: 'Information verified on',
    seasonNote: 'Season note',
    note: 'Note',
    official: 'official',
    indicative: 'indicative',
    usedFor: 'Used for',
    lines: 'Lines',
    stop: 'Stop',
    walk: 'Walk',
    parking: 'Parking',
    roads: 'Roads',
    destination: 'Destination',
    yes: 'Yes',
    no: 'No',
    onlineOnly: 'Tickets online only',
    bookingRecommended: 'Booking recommended',
    officialHours: 'Opening hours',
    openingHoursFallback: 'Check before visiting according to the current season and operator.',
    nudistBeach: 'Nudist beach',
    waterQuality: 'Water quality',
    bestTime: 'Best time',
    avoidIfPossible: 'Avoid if possible',
    swimmingType: 'Swimming type',
    crowdLevel: 'Crowds',
    placeType: 'Place type',
    category: 'Category',
  },
  de: {
    home: 'Euvida',
    readingTime: 'Lesezeit',
    readingTimeUnit: 'Min.',
    checked: 'Geprüft am',
    updated: 'Aktualisiert',
    country: 'Land',
    region: 'Region',
    featured: 'Empfohlen',
    quickInfo: 'Kurzüberblick',
    practicalInfo: 'Praktische Informationen',
    prices: 'Preise',
    access: 'Anreise & Transport',
    bookingUrl: 'Buchung unter:',
    sources: 'Quellen und Prüfung',
    sourcesIntro: 'Quellen zur Prüfung von Preisen, Betrieb, Regeln und praktischen Informationen.',
    photo: 'Foto',
    noImage: 'Bild nicht verfügbar',
    infoChecked: 'Informationen geprüft am',
    seasonNote: 'Saisonhinweis',
    note: 'Hinweis',
    official: 'offiziell',
    indicative: 'orientierend',
    usedFor: 'Verwendet für',
    lines: 'Linien',
    stop: 'Haltestelle',
    walk: 'Fußweg',
    parking: 'Parken',
    roads: 'Straßen',
    destination: 'Ziel',
    yes: 'Ja',
    no: 'Nein',
    onlineOnly: 'Tickets nur online',
    bookingRecommended: 'Reservierung empfohlen',
    officialHours: 'Öffnungszeiten',
    openingHoursFallback: 'Vor dem Besuch je nach Saison und Betreiber prüfen.',
    nudistBeach: 'FKK-Strand',
    waterQuality: 'Wasserqualität',
    bestTime: 'Beste Zeit',
    avoidIfPossible: 'Möglichst vermeiden',
    swimmingType: 'Badeart',
    crowdLevel: 'Andrang',
    placeType: 'Ortstyp',
    category: 'Kategorie',
  },
  fr: {
    home: 'Euvida',
    readingTime: 'Temps de lecture',
    readingTimeUnit: 'min de lecture',
    checked: 'Vérifié le',
    updated: 'Mis à jour',
    country: 'Pays',
    region: 'Région',
    featured: 'Recommandé',
    quickInfo: 'Aperçu rapide',
    practicalInfo: 'Informations pratiques',
    prices: 'Tarifs',
    access: 'Accès & transport',
    bookingUrl: 'Réservation sur :',
    sources: 'Sources et vérification',
    sourcesIntro: 'Sources utilisées pour vérifier les prix, les horaires, les règles et les informations pratiques.',
    photo: 'Photo',
    noImage: 'Image non disponible',
    infoChecked: 'Informations vérifiées le',
    seasonNote: 'Note saisonnière',
    note: 'Note',
    official: 'officiel',
    indicative: 'indicatif',
    usedFor: 'Utilisé pour',
    lines: 'Lignes',
    stop: 'Arrêt',
    walk: 'Marche',
    parking: 'Stationnement',
    roads: 'Routes',
    destination: 'Destination',
    yes: 'Oui',
    no: 'Non',
    onlineOnly: 'Billets uniquement en ligne',
    bookingRecommended: 'Réservation conseillée',
    officialHours: 'Horaires',
    openingHoursFallback: 'Vérifie avant la visite selon la saison et l’exploitant.',
    nudistBeach: 'Plage naturiste',
    waterQuality: 'Qualité de l’eau',
    bestTime: 'Meilleur moment',
    avoidIfPossible: 'À éviter si possible',
    swimmingType: 'Type de baignade',
    crowdLevel: 'Affluence',
    placeType: 'Type de lieu',
    category: 'Catégorie',
  },
  es: {
    home: 'Euvida',
    readingTime: 'Tiempo de lectura',
    readingTimeUnit: 'min de lectura',
    checked: 'Verificado el',
    updated: 'Actualizado',
    country: 'País',
    region: 'Región',
    featured: 'Recomendado',
    quickInfo: 'Resumen rápido',
    practicalInfo: 'Información práctica',
    prices: 'Precios',
    access: 'Acceso y transporte',
    bookingUrl: 'Reserva en:',
    sources: 'Fuentes y verificación',
    sourcesIntro: 'Fuentes usadas para verificar precios, funcionamiento, normas e información práctica.',
    photo: 'Foto',
    noImage: 'Imagen no disponible',
    infoChecked: 'Información verificada el',
    seasonNote: 'Nota de temporada',
    note: 'Nota',
    official: 'oficial',
    indicative: 'orientativo',
    usedFor: 'Usado para',
    lines: 'Líneas',
    stop: 'Parada',
    walk: 'A pie',
    parking: 'Aparcamiento',
    roads: 'Carreteras',
    destination: 'Destino',
    yes: 'Sí',
    no: 'No',
    onlineOnly: 'Entradas solo online',
    bookingRecommended: 'Reserva recomendada',
    officialHours: 'Horario',
    openingHoursFallback: 'Revisa antes de ir según temporada y operador.',
    nudistBeach: 'Playa nudista',
    waterQuality: 'Calidad del agua',
    bestTime: 'Mejor momento',
    avoidIfPossible: 'Evitar si es posible',
    swimmingType: 'Tipo de baño',
    crowdLevel: 'Afluencia',
    placeType: 'Tipo de lugar',
    category: 'Categoría',
  },
};

export const practicalLabels: LabelMap = {
  cs: {
    best_time: 'Nejlepší čas',
    ideal_for: 'Pro koho se hodí',
    good_for: 'Pro koho se hodí',
    target_group: 'Pro koho se hodí',
    who_it_suits: 'Pro koho se hodí',
    for_whom: 'Pro koho se hodí',
    time_needed: 'Kolik času si vyhradit',
    duration: 'Doba trvání',
    recommended_duration: 'Doporučená doba návštěvy',
    booking: 'Rezervace',
    reservation: 'Rezervace',
    booking_url: 'Rezervace',
    crowds: 'Vytíženost',
    transport: 'Doprava',
    public_transport: 'Veřejná doprava',
    parking: 'Parkování',
    address: 'Adresa',
    gps: 'GPS souřadnice',
    nearby_prices: 'Ceny v okolí',
    nearby: 'V okolí',
    nearby_attractions: 'Zajímavosti v okolí',
    combine_with: 'S čím spojit',
    watch_out: 'Na co si dát pozor',
    avoid_if: 'Kdy se raději vyhnout',
    safety_warning: 'Bezpečnostní upozornění',
    accessibility: 'Přístupnost',
    facilities: 'Zázemí',
    food: 'Občerstvení',
    food_drink_note: 'Občerstvení',
    equipment: 'Vybavení',
    dogs: 'Se psem',
    with_kids: 'S dětmi',
    water_quality: 'Kvalita vody',
    water_quality_note: 'Kvalita vody',
    season: 'Sezona',
    seasonality: 'Sezonnost',
    best_season: 'Nejlepší sezona',
    season_note: 'Sezónní poznámka',
    opening_hours: 'Otevírací doba',
    opening_hours_text: 'Otevírací doba',
    official_opening_hours: 'Otevírací doba',
    site_type: 'Typ místa',
    activities: 'Aktivity',
    highlights: 'Hlavní zajímavosti',
    main_attractions: 'Hlavní lákadla',
    lift: 'Lanovky & vleky',
    rental_service: 'Půjčovna & servis',
    bike_rental: 'Půjčovna kol',
    trail_stats: 'Statistiky trailů',
    trail_access: 'Vstup na traily',
    trail_list: 'Seznam trailů',
    trail_type: 'Typ trailů',
    trail_map: 'Mapa trailů',
    trail_map_url: 'Mapa trailů',
    route_info: 'Informace o trase',
    logistics: 'Logistika',
    recommendation: 'Doporučení',
    official_website: 'Oficiální web',
    website: 'Web',
    map: 'Mapa',
    note: 'Poznámka',
  },
  en: {
    best_time: 'Best time',
    ideal_for: 'Best for',
    good_for: 'Good for',
    target_group: 'Best for',
    who_it_suits: 'Who it suits',
    for_whom: 'Best for',
    time_needed: 'Time needed',
    duration: 'Duration',
    recommended_duration: 'Recommended visit time',
    booking: 'Booking',
    reservation: 'Reservation',
    booking_url: 'Booking',
    crowds: 'Crowds',
    transport: 'Transport',
    public_transport: 'Public transport',
    parking: 'Parking',
    address: 'Address',
    gps: 'GPS coordinates',
    nearby_prices: 'Nearby prices',
    nearby: 'Nearby',
    nearby_attractions: 'Nearby attractions',
    combine_with: 'Combine with',
    watch_out: 'Watch out for',
    avoid_if: 'Avoid if',
    safety_warning: 'Safety warning',
    accessibility: 'Accessibility',
    facilities: 'Facilities',
    food: 'Food & drink',
    food_drink_note: 'Food & drink',
    equipment: 'Equipment',
    dogs: 'With dogs',
    with_kids: 'With kids',
    water_quality: 'Water quality',
    water_quality_note: 'Water quality',
    season: 'Season',
    seasonality: 'Seasonality',
    best_season: 'Best season',
    season_note: 'Season note',
    opening_hours: 'Opening hours',
    opening_hours_text: 'Opening hours',
    official_opening_hours: 'Opening hours',
    site_type: 'Site type',
    activities: 'Activities',
    highlights: 'Highlights',
    main_attractions: 'Main attractions',
    lift: 'Lifts & cable cars',
    rental_service: 'Rental & service',
    bike_rental: 'Bike rental',
    trail_stats: 'Trail statistics',
    trail_access: 'Trail access',
    trail_list: 'Trail list',
    trail_type: 'Trail type',
    trail_map: 'Trail map',
    trail_map_url: 'Trail map',
    route_info: 'Route info',
    logistics: 'Logistics',
    recommendation: 'Recommendation',
    official_website: 'Official website',
    website: 'Website',
    map: 'Map',
    note: 'Note',
  },
  de: {
    best_time: 'Beste Zeit',
    ideal_for: 'Geeignet für',
    good_for: 'Geeignet für',
    target_group: 'Zielgruppe',
    who_it_suits: 'Geeignet für',
    for_whom: 'Geeignet für',
    time_needed: 'Benötigte Zeit',
    duration: 'Dauer',
    recommended_duration: 'Empfohlene Besuchszeit',
    booking: 'Reservierung',
    reservation: 'Reservierung',
    booking_url: 'Reservierung',
    crowds: 'Andrang',
    transport: 'Anreise',
    public_transport: 'Öffentliche Verkehrsmittel',
    parking: 'Parken',
    address: 'Adresse',
    gps: 'GPS-Koordinaten',
    nearby_prices: 'Preise in der Umgebung',
    nearby: 'In der Nähe',
    nearby_attractions: 'Sehenswürdigkeiten in der Nähe',
    combine_with: 'Kombinierbar mit',
    watch_out: 'Worauf achten',
    avoid_if: 'Besser vermeiden, wenn',
    safety_warning: 'Sicherheitshinweis',
    accessibility: 'Barrierefreiheit',
    facilities: 'Ausstattung',
    food: 'Essen & Trinken',
    food_drink_note: 'Essen & Trinken',
    equipment: 'Ausrüstung',
    dogs: 'Mit Hund',
    with_kids: 'Mit Kindern',
    water_quality: 'Wasserqualität',
    water_quality_note: 'Wasserqualität',
    season: 'Saison',
    seasonality: 'Saisonalität',
    best_season: 'Beste Saison',
    season_note: 'Saisonhinweis',
    opening_hours: 'Öffnungszeiten',
    opening_hours_text: 'Öffnungszeiten',
    official_opening_hours: 'Öffnungszeiten',
    site_type: 'Ortstyp',
    activities: 'Aktivitäten',
    highlights: 'Highlights',
    main_attractions: 'Wichtigste Attraktionen',
    lift: 'Lifte & Bahnen',
    rental_service: 'Verleih & Service',
    bike_rental: 'Bike-Verleih',
    trail_stats: 'Trail-Statistiken',
    trail_access: 'Trailzugang',
    trail_list: 'Trailliste',
    trail_type: 'Trailtyp',
    trail_map: 'Trailkarte',
    trail_map_url: 'Trailkarte',
    route_info: 'Routeninfo',
    logistics: 'Logistik',
    recommendation: 'Empfehlung',
    official_website: 'Offizielle Website',
    website: 'Website',
    map: 'Karte',
    note: 'Hinweis',
  },
  fr: {
    best_time: 'Meilleur moment',
    ideal_for: 'Idéal pour',
    good_for: 'Idéal pour',
    target_group: 'Public conseillé',
    who_it_suits: 'Pour qui',
    for_whom: 'Pour qui',
    time_needed: 'Temps à prévoir',
    duration: 'Durée',
    recommended_duration: 'Durée de visite conseillée',
    booking: 'Réservation',
    reservation: 'Réservation',
    booking_url: 'Réservation',
    crowds: 'Affluence',
    transport: 'Accès',
    public_transport: 'Transports en commun',
    parking: 'Stationnement',
    address: 'Adresse',
    gps: 'Coordonnées GPS',
    nearby_prices: 'Prix aux alentours',
    nearby: 'À proximité',
    nearby_attractions: 'Sites à proximité',
    combine_with: 'À combiner avec',
    watch_out: 'À surveiller',
    avoid_if: 'À éviter si',
    safety_warning: 'Alerte sécurité',
    accessibility: 'Accessibilité',
    facilities: 'Équipements',
    food: 'Restauration',
    food_drink_note: 'Restauration',
    equipment: 'Équipement',
    dogs: 'Avec chien',
    with_kids: 'Avec enfants',
    water_quality: 'Qualité de l’eau',
    water_quality_note: 'Qualité de l’eau',
    season: 'Saison',
    seasonality: 'Saisonnalité',
    best_season: 'Meilleure saison',
    season_note: 'Note saisonnière',
    opening_hours: 'Horaires',
    opening_hours_text: 'Horaires',
    official_opening_hours: 'Horaires',
    site_type: 'Type de lieu',
    activities: 'Activités',
    highlights: 'Points forts',
    main_attractions: 'Principales attractions',
    lift: 'Remontées mécaniques',
    rental_service: 'Location & service',
    bike_rental: 'Location de vélo',
    trail_stats: 'Statistiques des pistes',
    trail_access: 'Accès aux trails',
    trail_list: 'Liste des trails',
    trail_type: 'Type de trails',
    trail_map: 'Plan des pistes',
    trail_map_url: 'Plan des pistes',
    route_info: 'Infos itinéraire',
    logistics: 'Logistique',
    recommendation: 'Recommandation',
    official_website: 'Site officiel',
    website: 'Site web',
    map: 'Carte',
    note: 'Note',
  },
  es: {
    best_time: 'Mejor momento',
    ideal_for: 'Ideal para',
    good_for: 'Ideal para',
    target_group: 'Público recomendado',
    who_it_suits: 'Para quién',
    for_whom: 'Para quién',
    time_needed: 'Tiempo necesario',
    duration: 'Duración',
    recommended_duration: 'Duración recomendada de la visita',
    booking: 'Reserva',
    reservation: 'Reserva',
    booking_url: 'Reserva',
    crowds: 'Afluencia',
    transport: 'Transporte',
    public_transport: 'Transporte público',
    parking: 'Aparcamiento',
    address: 'Dirección',
    gps: 'Coordenadas GPS',
    nearby_prices: 'Precios cercanos',
    nearby: 'Cerca',
    nearby_attractions: 'Atracciones cercanas',
    combine_with: 'Combinar con',
    watch_out: 'A tener en cuenta',
    avoid_if: 'Evitar si',
    safety_warning: 'Aviso de seguridad',
    accessibility: 'Accesibilidad',
    facilities: 'Servicios',
    food: 'Comida y bebida',
    food_drink_note: 'Comida y bebida',
    equipment: 'Equipamiento',
    dogs: 'Con perros',
    with_kids: 'Con niños',
    water_quality: 'Calidad del agua',
    water_quality_note: 'Calidad del agua',
    season: 'Temporada',
    seasonality: 'Estacionalidad',
    best_season: 'Mejor temporada',
    season_note: 'Nota de temporada',
    opening_hours: 'Horario',
    opening_hours_text: 'Horario',
    official_opening_hours: 'Horario',
    site_type: 'Tipo de lugar',
    activities: 'Actividades',
    highlights: 'Puntos destacados',
    main_attractions: 'Principales atractivos',
    lift: 'Remontes',
    rental_service: 'Alquiler y servicio',
    bike_rental: 'Alquiler de bicis',
    trail_stats: 'Estadísticas de pistas',
    trail_access: 'Acceso a trails',
    trail_list: 'Lista de trails',
    trail_type: 'Tipo de trails',
    trail_map: 'Mapa de pistas',
    trail_map_url: 'Mapa de pistas',
    route_info: 'Información de ruta',
    logistics: 'Logística',
    recommendation: 'Recomendación',
    official_website: 'Web oficial',
    website: 'Web',
    map: 'Mapa',
    note: 'Nota',
  },
};

export const durationLabels: LabelMap = {
  cs: {
    default: 'Kolik času si vyhradit',
    landmark: 'Doporučený čas návštěvy',
    museum: 'Doporučený čas návštěvy',
    castle: 'Doporučený čas návštěvy',
    chateau: 'Doporučený čas návštěvy',
    palace: 'Doporučený čas návštěvy',
    nature: 'Doporučený čas v lokalitě',
    natural_swimming: 'Doporučená délka pobytu',
    swimming_pool: 'Doporučená délka pobytu',
    beach: 'Doporučená délka pobytu',
    trail: 'Čas na trase',
    cycling_route: 'Čas na trase',
    ski_area: 'Doporučený čas na místě',
    camping: 'Kolik času si vyhradit',
    bike_trail: 'Kolik času si vyhradit',
  },
  en: {
    default: 'Time needed',
    landmark: 'Recommended visit time',
    museum: 'Recommended visit time',
    castle: 'Recommended visit time',
    chateau: 'Recommended visit time',
    palace: 'Recommended visit time',
    nature: 'Recommended time on site',
    natural_swimming: 'Recommended stay',
    swimming_pool: 'Recommended stay',
    beach: 'Recommended stay',
    trail: 'Time on route',
    cycling_route: 'Time on route',
    ski_area: 'Recommended time on site',
    camping: 'Time needed',
    bike_trail: 'Time needed',
  },
  de: {
    default: 'Benötigte Zeit',
    landmark: 'Empfohlene Besuchszeit',
    museum: 'Empfohlene Besuchszeit',
    castle: 'Empfohlene Besuchszeit',
    chateau: 'Empfohlene Besuchszeit',
    palace: 'Empfohlene Besuchszeit',
    nature: 'Empfohlene Zeit vor Ort',
    natural_swimming: 'Empfohlene Aufenthaltsdauer',
    swimming_pool: 'Empfohlene Aufenthaltsdauer',
    beach: 'Empfohlene Aufenthaltsdauer',
    trail: 'Zeit auf der Route',
    cycling_route: 'Zeit auf der Route',
    ski_area: 'Empfohlene Zeit vor Ort',
    camping: 'Benötigte Zeit',
    bike_trail: 'Benötigte Zeit',
  },
  fr: {
    default: 'Temps à prévoir',
    landmark: 'Temps de visite conseillé',
    museum: 'Temps de visite conseillé',
    castle: 'Temps de visite conseillé',
    chateau: 'Temps de visite conseillé',
    palace: 'Temps de visite conseillé',
    nature: 'Temps conseillé sur place',
    natural_swimming: 'Durée de séjour conseillée',
    swimming_pool: 'Durée de séjour conseillée',
    beach: 'Durée de séjour conseillée',
    trail: 'Temps sur l’itinéraire',
    cycling_route: 'Temps sur l’itinéraire',
    ski_area: 'Temps conseillé sur place',
    camping: 'Temps à prévoir',
    bike_trail: 'Temps à prévoir',
  },
  es: {
    default: 'Tiempo necesario',
    landmark: 'Tiempo recomendado de visita',
    museum: 'Tiempo recomendado de visita',
    castle: 'Tiempo recomendado de visita',
    chateau: 'Tiempo recomendado de visita',
    palace: 'Tiempo recomendado de visita',
    nature: 'Tiempo recomendado en el lugar',
    natural_swimming: 'Duración recomendada de estancia',
    swimming_pool: 'Duración recomendada de estancia',
    beach: 'Duración recomendada de estancia',
    trail: 'Tiempo en la ruta',
    cycling_route: 'Tiempo en la ruta',
    ski_area: 'Tiempo recomendado en el lugar',
    camping: 'Tiempo necesario',
    bike_trail: 'Tiempo necesario',
  },
};

export const placeTypeLabels: LabelMap = {
  cs: {
    landmark: 'památka',
    museum: 'muzeum',
    castle: 'hrad',
    chateau: 'zámek',
    palace: 'palác',
    nature: 'příroda',
    natural_swimming: 'přírodní koupání',
    swimming_pool: 'koupaliště',
    beach: 'pláž',
    trail: 'turistická trasa',
    cycling_route: 'cyklostezka',
    ski_area: 'lyžařský areál',
    camping: 'kemp',
    bike_trail: 'bike park',
  },
  en: {
    landmark: 'landmark',
    museum: 'museum',
    castle: 'castle',
    chateau: 'chateau',
    palace: 'palace',
    nature: 'nature',
    natural_swimming: 'natural swimming',
    swimming_pool: 'swimming pool',
    beach: 'beach',
    trail: 'trail',
    cycling_route: 'cycling route',
    ski_area: 'ski area',
    camping: 'camping',
    bike_trail: 'bike park',
  },
  de: {
    landmark: 'Sehenswürdigkeit',
    museum: 'Museum',
    castle: 'Burg',
    chateau: 'Schloss',
    palace: 'Palast',
    nature: 'Natur',
    natural_swimming: 'Naturbad',
    swimming_pool: 'Freibad',
    beach: 'Strand',
    trail: 'Wanderroute',
    cycling_route: 'Radroute',
    ski_area: 'Skigebiet',
    camping: 'Campingplatz',
    bike_trail: 'Bikepark',
  },
  fr: {
    landmark: 'site remarquable',
    museum: 'musée',
    castle: 'château fort',
    chateau: 'château',
    palace: 'palais',
    nature: 'nature',
    natural_swimming: 'baignade naturelle',
    swimming_pool: 'piscine',
    beach: 'plage',
    trail: 'itinéraire de randonnée',
    cycling_route: 'itinéraire cyclable',
    ski_area: 'domaine skiable',
    camping: 'camping',
    bike_trail: 'bike park',
  },
  es: {
    landmark: 'monumento',
    museum: 'museo',
    castle: 'castillo',
    chateau: 'palacio',
    palace: 'palacio',
    nature: 'naturaleza',
    natural_swimming: 'baño natural',
    swimming_pool: 'piscina',
    beach: 'playa',
    trail: 'ruta de senderismo',
    cycling_route: 'ruta ciclista',
    ski_area: 'estación de esquí',
    camping: 'camping',
    bike_trail: 'bike park',
  },
};

export const crowdLevelLabels: LabelMap = {
  cs: {
    low: 'nízká',
    medium: 'střední',
    high: 'vysoká',
    very_high: 'velmi vysoká',
    high_in_hot_weather: 'vysoká za horkého počasí',
    high_in_peak_season: 'vysoká v hlavní sezoně',
    very_high_in_peak_season: 'velmi vysoká v hlavní sezoně',
  },
  en: {
    low: 'low',
    medium: 'medium',
    high: 'high',
    very_high: 'very high',
    high_in_hot_weather: 'high in hot weather',
    high_in_peak_season: 'high in peak season',
    very_high_in_peak_season: 'very high in peak season',
  },
  de: {
    low: 'niedrig',
    medium: 'mittel',
    high: 'hoch',
    very_high: 'sehr hoch',
    high_in_hot_weather: 'hoch bei heißem Wetter',
    high_in_peak_season: 'hoch in der Hauptsaison',
    very_high_in_peak_season: 'sehr hoch in der Hauptsaison',
  },
  fr: {
    low: 'faible',
    medium: 'moyenne',
    high: 'élevée',
    very_high: 'très élevée',
    high_in_hot_weather: 'élevée par temps chaud',
    high_in_peak_season: 'élevée en haute saison',
    very_high_in_peak_season: 'très élevée en haute saison',
  },
  es: {
    low: 'baja',
    medium: 'media',
    high: 'alta',
    very_high: 'muy alta',
    high_in_hot_weather: 'alta con calor',
    high_in_peak_season: 'alta en temporada alta',
    very_high_in_peak_season: 'muy alta en temporada alta',
  },
};

export const timeKeyLabels: LabelMap = {
  cs: {
    spring: 'jaro',
    summer: 'léto',
    autumn: 'podzim',
    winter: 'zima',
    early_morning: 'brzy ráno',
    morning: 'ráno',
    weekday_morning: 'ráno ve všední den',
    summer_morning: 'letní ráno',
    late_afternoon: 'pozdní odpoledne',
    sunset: 'západ slunce',
    sunrise: 'východ slunce',
    weekdays: 'všední dny',
    weekend: 'víkend',
    peak_season: 'hlavní sezona',
    off_season: 'mimo sezonu',
    hot_weekend_midday: 'horké víkendové poledne',
    midday: 'poledne',
  },
  en: {
    spring: 'spring',
    summer: 'summer',
    autumn: 'autumn',
    winter: 'winter',
    early_morning: 'early morning',
    morning: 'morning',
    weekday_morning: 'weekday morning',
    summer_morning: 'summer morning',
    late_afternoon: 'late afternoon',
    sunset: 'sunset',
    sunrise: 'sunrise',
    weekdays: 'weekdays',
    weekend: 'weekend',
    peak_season: 'peak season',
    off_season: 'off season',
    hot_weekend_midday: 'hot weekend midday',
    midday: 'midday',
  },
  de: {
    spring: 'Frühling',
    summer: 'Sommer',
    autumn: 'Herbst',
    winter: 'Winter',
    early_morning: 'früher Morgen',
    morning: 'Morgen',
    weekday_morning: 'Morgen an Werktagen',
    summer_morning: 'Sommermorgen',
    late_afternoon: 'später Nachmittag',
    sunset: 'Sonnenuntergang',
    sunrise: 'Sonnenaufgang',
    weekdays: 'Werktage',
    weekend: 'Wochenende',
    peak_season: 'Hauptsaison',
    off_season: 'Nebensaison',
    hot_weekend_midday: 'heißer Wochenendmittag',
    midday: 'Mittag',
  },
  fr: {
    spring: 'printemps',
    summer: 'été',
    autumn: 'automne',
    winter: 'hiver',
    early_morning: 'tôt le matin',
    morning: 'matin',
    weekday_morning: 'matin en semaine',
    summer_morning: 'matin d’été',
    late_afternoon: 'fin d’après-midi',
    sunset: 'coucher du soleil',
    sunrise: 'lever du soleil',
    weekdays: 'jours de semaine',
    weekend: 'week-end',
    peak_season: 'haute saison',
    off_season: 'hors saison',
    hot_weekend_midday: 'midi de week-end par forte chaleur',
    midday: 'midi',
  },
  es: {
    spring: 'primavera',
    summer: 'verano',
    autumn: 'otoño',
    winter: 'invierno',
    early_morning: 'temprano por la mañana',
    morning: 'mañana',
    weekday_morning: 'mañana entre semana',
    summer_morning: 'mañana de verano',
    late_afternoon: 'última hora de la tarde',
    sunset: 'puesta de sol',
    sunrise: 'amanecer',
    weekdays: 'días laborables',
    weekend: 'fin de semana',
    peak_season: 'temporada alta',
    off_season: 'temporada baja',
    hot_weekend_midday: 'mediodía caluroso de fin de semana',
    midday: 'mediodía',
  },
};

export const swimmingTypeLabels: LabelMap = {
  cs: {
    natural: 'přírodní voda',
    lake: 'jezero',
    pond: 'rybník',
    reservoir: 'přehrada',
    river: 'řeka',
    biotope: 'biotop',
    outdoor_pool: 'venkovní koupaliště',
    indoor_pool: 'krytý bazén',
  },
  en: {
    natural: 'natural water',
    lake: 'lake',
    pond: 'pond',
    reservoir: 'reservoir',
    river: 'river',
    biotope: 'biotope',
    outdoor_pool: 'outdoor pool',
    indoor_pool: 'indoor pool',
  },
  de: {
    natural: 'Naturwasser',
    lake: 'See',
    pond: 'Teich',
    reservoir: 'Stausee',
    river: 'Fluss',
    biotope: 'Biotop',
    outdoor_pool: 'Freibad',
    indoor_pool: 'Hallenbad',
  },
  fr: {
    natural: 'eau naturelle',
    lake: 'lac',
    pond: 'étang',
    reservoir: 'réservoir',
    river: 'rivière',
    biotope: 'biotope',
    outdoor_pool: 'piscine extérieure',
    indoor_pool: 'piscine couverte',
  },
  es: {
    natural: 'agua natural',
    lake: 'lago',
    pond: 'estanque',
    reservoir: 'embalse',
    river: 'río',
    biotope: 'biotopo',
    outdoor_pool: 'piscina exterior',
    indoor_pool: 'piscina cubierta',
  },
};

export const categoryLabels: LabelMap = {
  cs: {
    landmark: 'Památky',
    city: 'Města',
    nature: 'Příroda',
    place: 'Zajímavá místa',
    places: 'Zajímavá místa',
    natural_swimming: 'Přírodní koupání',
    fkk: 'FKK pláže',
    trail: 'Trasa',
    cycling: 'Cyklostezka',
    cycling_route: 'Cyklostezka',
    castle: 'Hrad',
    chateau: 'Zámek',
    ski: 'Lyžařský areál',
    ski_area: 'Lyžařský areál',
    beach: 'Pláže',
    camping: 'Kempy',
    bike_trail: 'Bikeparky a traily',
    city_tip: 'Tip do města',
    trip: 'Výlety',
    trips: 'Výlety',
  },
  en: {
    landmark: 'Landmarks',
    city: 'Cities',
    nature: 'Nature',
    place: 'Places to visit',
    places: 'Places to visit',
    natural_swimming: 'Natural swimming',
    fkk: 'Naturist beaches',
    trail: 'Trail',
    cycling: 'Cycling route',
    cycling_route: 'Cycling route',
    castle: 'Castle',
    chateau: 'Chateau',
    ski: 'Ski area',
    ski_area: 'Ski area',
    beach: 'Beaches',
    camping: 'Camping',
    bike_trail: 'Bike parks and trails',
    city_tip: 'City tip',
    trip: 'Trips',
    trips: 'Trips',
  },
  de: {
    landmark: 'Sehenswürdigkeiten',
    city: 'Städte',
    nature: 'Natur',
    place: 'Sehenswerte Orte',
    places: 'Sehenswerte Orte',
    natural_swimming: 'Naturbaden',
    fkk: 'FKK-Strände',
    trail: 'Route',
    cycling: 'Radroute',
    cycling_route: 'Radroute',
    castle: 'Burg',
    chateau: 'Schloss',
    ski: 'Skigebiet',
    ski_area: 'Skigebiet',
    beach: 'Strände',
    camping: 'Camping',
    bike_trail: 'Bikeparks und Trails',
    city_tip: 'Stadttipp',
    trip: 'Ausflüge',
    trips: 'Ausflüge',
  },
  fr: {
    landmark: 'Monuments',
    city: 'Villes',
    nature: 'Nature',
    place: 'Lieux à voir',
    places: 'Lieux à voir',
    natural_swimming: 'Baignade naturelle',
    fkk: 'Plages naturistes',
    trail: 'Itinéraire',
    cycling: 'Itinéraire cyclable',
    cycling_route: 'Itinéraire cyclable',
    castle: 'Château fort',
    chateau: 'Château',
    ski: 'Domaine skiable',
    ski_area: 'Domaine skiable',
    beach: 'Plages',
    camping: 'Camping',
    bike_trail: 'Bike parks et trails',
    city_tip: 'Idée en ville',
    trip: 'Excursions',
    trips: 'Excursions',
  },
  es: {
    landmark: 'Monumentos',
    city: 'Ciudades',
    nature: 'Naturaleza',
    place: 'Lugares que ver',
    places: 'Lugares que ver',
    natural_swimming: 'Baño natural',
    fkk: 'Playas naturistas',
    trail: 'Ruta',
    cycling: 'Ruta ciclista',
    cycling_route: 'Ruta ciclista',
    castle: 'Castillo',
    chateau: 'Palacio',
    ski: 'Estación de esquí',
    ski_area: 'Estación de esquí',
    beach: 'Playas',
    camping: 'Camping',
    bike_trail: 'Bike parks y trails',
    city_tip: 'Plan urbano',
    trip: 'Excursiones',
    trips: 'Excursiones',
  },
};

export const sourceTypeLabels: LabelMap = {
  cs: {
    official: 'oficiální',
    tourism_board: 'turistická organizace',
    municipality: 'obec',
    practical_directory: 'praktický přehled',
  },
  en: {
    official: 'official',
    tourism_board: 'tourism board',
    municipality: 'municipality',
    practical_directory: 'practical directory',
  },
  de: {
    official: 'offiziell',
    tourism_board: 'Tourismusverband',
    municipality: 'Gemeinde',
    practical_directory: 'praktisches Verzeichnis',
  },
  fr: {
    official: 'officiel',
    tourism_board: 'office de tourisme',
    municipality: 'municipalité',
    practical_directory: 'annuaire pratique',
  },
  es: {
    official: 'oficial',
    tourism_board: 'oficina de turismo',
    municipality: 'municipio',
    practical_directory: 'directorio práctico',
  },
};

export const priceCategoryLabels: LabelMap = {
  cs: {
    ticket: 'Vstupné',
    lift_ticket: 'Lanovka a bike ticket',
    package: 'Balíčky',
    beach_access: 'Vstup k vodě',
    accommodation_person: 'Osoby',
    accommodation_unit: 'Ubytování a místa',
    vehicle: 'Vozidla',
    pet: 'Psi a domácí zvířata',
    tax: 'Poplatky',
    parking: 'Parkování',
    rental: 'Půjčovny',
    protective_gear: 'Chrániče a vybavení',
    activity: 'Aktivity',
    service: 'Služby',
    food_drink: 'Jídlo a pití',
    accommodation: 'Ubytování',
    rules: 'Pravidla',
    adult: 'Dospělí',
    child: 'Děti',
    reduced: 'Zlevněné',
    family: 'Rodiny',
    locker: 'Skříňky',
  },
  en: {
    ticket: 'Admission',
    lift_ticket: 'Lift and bike ticket',
    package: 'Packages',
    beach_access: 'Beach access',
    accommodation_person: 'People',
    accommodation_unit: 'Accommodation and pitches',
    vehicle: 'Vehicles',
    pet: 'Dogs and pets',
    tax: 'Fees',
    parking: 'Parking',
    rental: 'Rentals',
    protective_gear: 'Protective gear and equipment',
    activity: 'Activities',
    service: 'Services',
    food_drink: 'Food and drink',
    accommodation: 'Accommodation',
    rules: 'Rules',
    adult: 'Adults',
    child: 'Children',
    reduced: 'Reduced',
    family: 'Families',
    locker: 'Lockers',
  },
  de: {
    ticket: 'Eintritt',
    lift_ticket: 'Lift- und Bike-Ticket',
    package: 'Pakete',
    beach_access: 'Zugang zum Wasser',
    accommodation_person: 'Personen',
    accommodation_unit: 'Unterkunft und Stellplätze',
    vehicle: 'Fahrzeuge',
    pet: 'Hunde und Haustiere',
    tax: 'Gebühren',
    parking: 'Parken',
    rental: 'Verleih',
    protective_gear: 'Protektoren und Ausrüstung',
    activity: 'Aktivitäten',
    service: 'Services',
    food_drink: 'Essen und Trinken',
    accommodation: 'Unterkunft',
    rules: 'Regeln',
    adult: 'Erwachsene',
    child: 'Kinder',
    reduced: 'Ermäßigt',
    family: 'Familien',
    locker: 'Schließfächer',
  },
  fr: {
    ticket: 'Entrée',
    lift_ticket: 'Remontée et bike ticket',
    package: 'Forfaits',
    beach_access: 'Accès à la baignade',
    accommodation_person: 'Personnes',
    accommodation_unit: 'Hébergement et emplacements',
    vehicle: 'Véhicules',
    pet: 'Chiens et animaux',
    tax: 'Frais',
    parking: 'Stationnement',
    rental: 'Locations',
    protective_gear: 'Protections et équipement',
    activity: 'Activités',
    service: 'Services',
    food_drink: 'Restauration',
    accommodation: 'Hébergement',
    rules: 'Règles',
    adult: 'Adultes',
    child: 'Enfants',
    reduced: 'Tarif réduit',
    family: 'Familles',
    locker: 'Casiers',
  },
  es: {
    ticket: 'Entrada',
    lift_ticket: 'Remonte y bike ticket',
    package: 'Paquetes',
    beach_access: 'Acceso a la playa',
    accommodation_person: 'Personas',
    accommodation_unit: 'Alojamiento y parcelas',
    vehicle: 'Vehículos',
    pet: 'Perros y mascotas',
    tax: 'Tasas',
    parking: 'Aparcamiento',
    rental: 'Alquileres',
    protective_gear: 'Protecciones y equipamiento',
    activity: 'Actividades',
    service: 'Servicios',
    food_drink: 'Comida y bebida',
    accommodation: 'Alojamiento',
    rules: 'Normas',
    adult: 'Adultos',
    child: 'Niños',
    reduced: 'Reducida',
    family: 'Familias',
    locker: 'Taquillas',
  },
};

export const accessModeLabels: LabelMap = {
  cs: {
    walk: 'Pěšky',
    metro: 'Metro',
    tram: 'Tramvaj',
    bus: 'Autobus',
    train: 'Vlak',
    public_transport: 'Veřejná doprava',
    train_bus: 'vlak + autobus',
    car: 'Auto',
    parking: 'Parkování',
    taxi: 'Taxi',
    bike: 'Kolo',
    ferry: 'trajekt',
    boat: 'Loď',
    cable_car: 'Lanovka',
    funicular: 'pozemní lanovka',
    shuttle: 'shuttle',
    organized_tour: 'organizovaný výlet',
    plane: 'letadlo',
    other: 'jiná doprava',
  },
  en: {
    walk: 'walk',
    metro: 'metro',
    tram: 'tram',
    bus: 'bus',
    train: 'train',
    public_transport: 'public transport',
    train_bus: 'train + bus',
    car: 'car',
    parking: 'parking',
    taxi: 'taxi',
    bike: 'bike',
    ferry: 'ferry',
    boat: 'boat',
    cable_car: 'cable car',
    funicular: 'funicular',
    shuttle: 'shuttle',
    organized_tour: 'organized tour',
    plane: 'plane',
    other: 'other transport',
  },
  de: {
    walk: 'zu Fuß',
    metro: 'Metro',
    tram: 'Straßenbahn',
    bus: 'Bus',
    train: 'Zug',
    public_transport: 'öffentliche Verkehrsmittel',
    train_bus: 'Zug + Bus',
    car: 'Auto',
    parking: 'Parken',
    taxi: 'Taxi',
    bike: 'Fahrrad',
    ferry: 'Fähre',
    boat: 'Boot',
    cable_car: 'Seilbahn',
    funicular: 'Standseilbahn',
    shuttle: 'Shuttle',
    organized_tour: 'organisierte Tour',
    plane: 'Flugzeug',
    other: 'andere Anreise',
  },
  fr: {
    walk: 'à pied',
    metro: 'métro',
    tram: 'tramway',
    bus: 'bus',
    train: 'train',
    public_transport: 'transports publics',
    train_bus: 'train + bus',
    car: 'voiture',
    parking: 'stationnement',
    taxi: 'taxi',
    bike: 'vélo',
    ferry: 'ferry',
    boat: 'bateau',
    cable_car: 'téléphérique',
    funicular: 'funiculaire',
    shuttle: 'navette',
    organized_tour: 'excursion organisée',
    plane: 'avion',
    other: 'autre transport',
  },
  es: {
    walk: 'a pie',
    metro: 'metro',
    tram: 'tranvía',
    bus: 'autobús',
    train: 'tren',
    public_transport: 'transporte público',
    train_bus: 'tren + autobús',
    car: 'coche',
    parking: 'aparcamiento',
    taxi: 'taxi',
    bike: 'bicicleta',
    ferry: 'ferry',
    boat: 'barco',
    cable_car: 'teleférico',
    funicular: 'funicular',
    shuttle: 'lanzadera',
    organized_tour: 'excursión organizada',
    plane: 'avión',
    other: 'otro transporte',
  },
};

export const recommendedLabels: Record<SupportedLocale, string> = {
  cs: 'Doporučeno',
  en: 'Recommended',
  de: 'Empfohlen',
  fr: 'Recommandé',
  es: 'Recomendado',
};

export function getArticleLabel(locale: string, key: string): string {
  const currentLocale = normalizeLocale(locale);
  return articleUiLabels[currentLocale][key] ?? articleUiLabels.cs[key] ?? key;
}

export function getMappedLabel(
  labels: LabelMap,
  locale: string,
  key: string | null | undefined
): string | null {
  if (!key) {
    return null;
  }

  const currentLocale = normalizeLocale(locale);
  return labels[currentLocale][key] ?? labels.cs[key] ?? null;
}

function humanizeTechnicalValue(value: string | null | undefined): string | null {
  if (!value) {
    return null;
  }

  const humanized = value
    .replace(/[_-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

  if (!humanized) {
    return null;
  }

  return humanized.charAt(0).toUpperCase() + humanized.slice(1);
}

export function getCategoryLabel(
  category: string | null | undefined,
  locale: string
): string | null {
  const normalizedCategory =
    category?.trim().toLocaleLowerCase('cs-CZ') === 'místa' ? 'places' : category;

  return (
    getMappedLabel(categoryLabels, locale, normalizedCategory) ??
    humanizeTechnicalValue(normalizedCategory)
  );
}

export function getModeLabel(
  mode: string | null | undefined,
  locale: string
): string | null {
  return getMappedLabel(accessModeLabels, locale, mode);
}

export function getBooleanLabel(
  value: boolean | null | undefined,
  locale: string
): string | null {
  if (typeof value !== 'boolean') {
    return null;
  }

  return getArticleLabel(locale, value ? 'yes' : 'no');
}

export function getDurationLabel(locale: string, placeType?: string | null): string {
  const currentLocale = normalizeLocale(locale);
  const key = placeType ?? 'default';

  return (
    durationLabels[currentLocale][key] ??
    durationLabels[currentLocale].default ??
    durationLabels.cs.default
  );
}
