import { normalizeLocale } from './articleLocalization';
import type { SupportedLocale } from './articleTypes';

type DestinationLabelMap = Record<SupportedLocale, Record<string, string>>;

const labels: DestinationLabelMap = {
  cs: {
    home: 'Domů',
    articlesAndGuides: 'Bikeparky a traily',
    countryArticles: 'Bikeparky a trailcentra',
    regionArticles: 'Bikeparky v regionu',
    regionCategories: 'Vlastnosti & filtry',
    featuredArticles: 'Doporučené bikeparky',
    latestGuides: 'Nejnovější bikeparky',
    latestArticles: 'Nejnovější bikeparky',
    articleCategories: 'Vlastnosti & filtry',
    destinations: 'Země & regiony',
    destinationsIntro: 'Vyberte si zemi a prozkoumejte nejlepší bikeparky, lanovky, trailcentra a podmínky pro ježdění.',
    countries: 'Země',
    exploreCountry: 'Zobrazit bikeparky v zemi',
    regions: 'Regiony',
    selectedRegions: 'Výběr bikových regionů',
    exploreRegion: 'Zobrazit bikeparky',
    noArticles: 'Zatím zde nejsou žádné bikeparky.',
    noCountryArticles: 'V této zemi zatím nejsou v katalogu žádné bikeparky.',
    noRegionArticles: 'V tomto regionu zatím nejsou žádné bikeparky.',
    noFilteredArticles: 'Pro tento výběr filtrů nebyl nalezen žádný bikepark.',
    loading: 'Načítám...',
    loadError: 'Bikeparky se teď nepodařilo načíst.',
    readMore: 'Detail bikeparku',
    travelGuide: 'Průvodce bikeparky',
    countryGuide: 'Bikeparky v zemi',
    regionGuide: 'Bikeparky v regionu',
    planning: 'MTB plánování',
    routes: 'Tratě a lanovky',
    quickChoices: 'Rychlé volby',
    filterArticles: 'Filtrovat bikeparky',
    allCategories: 'Všechny areály',
    allArticles: 'Všechny bikeparky',
    showAllArticles: 'Zobrazit všechny bikeparky',
    showMoreArticles: 'Zobrazit další',
    allArticlesIntro: 'Kompletní katalog evropských bikeparků a trailcenter s ověřenými informacemi o lanovkách, tratích a zázemí.',
    searchResults: 'Výsledky hledání',
    searchResultsFor: 'Výsledky hledání pro',
    articleSearchPlaceholder: 'Hledat bikepark, trailcentrum, lokalitu...',
    articleSearchButton: 'Hledat',
    noSearchResults: 'Pro tento dotaz jsme nenašli žádný bikepark.',
    allCountries: 'Všechny země',
    showAllCountries: 'Zobrazit všechny země',
    allRegions: 'Všechny regiony',
    articlesCount: 'Bikeparků',
    regionsCount: 'Regionů',
    categoryCount: 'Vlastností',
    currentWeather: 'Aktuální počasí',
    averageTemperatures: 'Průměrné teploty',
    spring: 'Jaro',
    summer: 'Léto',
    autumn: 'Podzim',
    winter: 'Zima',
    air: 'Vzduch',
    sea: 'Voda',
    noData: 'Bez dat',
    language: 'Jazyk',
    generalInfo: 'Obecné informace',
    travelTourism: 'Bikeparky & tratě',
    lifeWork: 'Doprava & pobyt',
    cultureFood: 'Zázemí & servis',
    practicalCautions: 'Praktické rady pro jezdce',
    natureAndTrips: 'Tratě a traily',
    historyAtmosphere: 'Zázemí a atmosféra',
    transportAndLife: 'Doprava a ubytování',
    backToOverview: 'Zpět na přehled',
    backToHome: 'Zpět na hlavní stránku',
    backToCountry: 'Zpět na zemi',
    savedFavorite: 'Uloženo v oblíbených',
    addFavorite: 'Přidat do oblíbených',
  },
  en: {
    home: 'Home',
    articlesAndGuides: 'Bike parks & trails',
    countryArticles: 'Bike parks & trail centers',
    regionArticles: 'Bike parks in this region',
    regionCategories: 'Features & filters',
    featuredArticles: 'Featured bike parks',
    latestGuides: 'Latest bike parks',
    latestArticles: 'Latest bike parks',
    articleCategories: 'Features & filters',
    destinations: 'Countries & regions',
    destinationsIntro: 'Choose a country and explore top bike parks, uplifts, trail networks, and riding conditions.',
    countries: 'Countries',
    exploreCountry: 'Explore country bike parks',
    regions: 'Regions',
    selectedRegions: 'Selected bike regions',
    exploreRegion: 'Explore bike parks',
    noArticles: 'No bike parks here yet.',
    noCountryArticles: 'There are no bike parks listed for this country yet.',
    noRegionArticles: 'There are no bike parks for this region yet.',
    noFilteredArticles: 'No bike parks matched this filter combination.',
    loading: 'Loading...',
    loadError: 'The bike parks could not be loaded right now.',
    readMore: 'View bike park',
    travelGuide: 'Bike park guide',
    countryGuide: 'Bike parks in country',
    regionGuide: 'Bike parks in region',
    planning: 'MTB planning',
    routes: 'Trails & uplifts',
    quickChoices: 'Quick filters',
    filterArticles: 'Filter bike parks',
    allCategories: 'All parks',
    allArticles: 'All bike parks',
    showAllArticles: 'Show all bike parks',
    showMoreArticles: 'Show more',
    allArticlesIntro: 'A complete catalog of European bike parks and trail centers with verified details on lifts, trails, and facilities.',
    searchResults: 'Search results',
    searchResultsFor: 'Search results for',
    articleSearchPlaceholder: 'Search bike parks, trail centers, locations...',
    articleSearchButton: 'Search',
    noSearchResults: 'No bike parks found for this search.',
    allCountries: 'All countries',
    showAllCountries: 'Show all countries',
    allRegions: 'All regions',
    articlesCount: 'Bike parks',
    regionsCount: 'Regions',
    categoryCount: 'Features',
    currentWeather: 'Current weather',
    averageTemperatures: 'Average temperatures',
    spring: 'Spring',
    summer: 'Summer',
    autumn: 'Autumn',
    winter: 'Winter',
    air: 'Air',
    sea: 'Water',
    noData: 'No data',
    language: 'Language',
    generalInfo: 'General info',
    travelTourism: 'Bike parks & trails',
    lifeWork: 'Transport & stay',
    cultureFood: 'Services & facilities',
    practicalCautions: 'Rider safety & tips',
    natureAndTrips: 'Trails & riding',
    historyAtmosphere: 'Facilities & vibe',
    transportAndLife: 'Transport & accommodation',
    backToOverview: 'Back to overview',
    backToHome: 'Back to homepage',
    backToCountry: 'Back to country',
    savedFavorite: 'Saved to favorites',
    addFavorite: 'Add to favorites',
  },
  de: {
    home: 'Startseite',
    articlesAndGuides: 'Bikeparks & Trails',
    countryArticles: 'Bikeparks & Trailcenter',
    regionArticles: 'Bikeparks in dieser Region',
    regionCategories: 'Merkmale & Filter',
    featuredArticles: 'Empfohlene Bikeparks',
    latestGuides: 'Neueste Bikeparks',
    latestArticles: 'Neueste Bikeparks',
    articleCategories: 'Merkmale & Filter',
    destinations: 'Länder & Regionen',
    destinationsIntro: 'Wähle ein Land und entdecke Top-Bikeparks, Bergbahnen, Trailnetze und Streckenbedingungen.',
    countries: 'Länder',
    exploreCountry: 'Bikeparks im Land entdecken',
    regions: 'Regionen',
    selectedRegions: 'Ausgewählte Bike-Regionen',
    exploreRegion: 'Bikeparks erkunden',
    noArticles: 'Hier gibt es noch keine Bikeparks.',
    noCountryArticles: 'Für dieses Land sind noch keine Bikeparks gelistet.',
    noRegionArticles: 'Für diese Region gibt es noch keine Bikeparks.',
    noFilteredArticles: 'Für diese Filterkombination wurde kein Bikepark gefunden.',
    loading: 'Wird geladen...',
    loadError: 'Die Bikeparks konnten gerade nicht geladen werden.',
    readMore: 'Bikepark ansehen',
    travelGuide: 'Bikepark-Guide',
    countryGuide: 'Bikeparks im Land',
    regionGuide: 'Bikeparks in der Region',
    planning: 'MTB-Planung',
    routes: 'Strecken & Lifte',
    quickChoices: 'Schnellauswahl',
    filterArticles: 'Bikeparks filtern',
    allCategories: 'Alle Parks',
    allArticles: 'Alle Bikeparks',
    showAllArticles: 'Alle Bikeparks anzeigen',
    showMoreArticles: 'Mehr anzeigen',
    allArticlesIntro: 'Ein kompletter Katalog europäischer Bikeparks und Trailcenter mit geprüften Infos zu Liften, Trails und Service.',
    searchResults: 'Suchergebnisse',
    searchResultsFor: 'Suchergebnisse für',
    articleSearchPlaceholder: 'Bikepark, Trailcenter, Ort suchen...',
    articleSearchButton: 'Suchen',
    noSearchResults: 'Für diese Suche wurden keine Bikeparks gefunden.',
    allCountries: 'Alle Länder',
    showAllCountries: 'Alle Länder anzeigen',
    allRegions: 'Alle Regionen',
    articlesCount: 'Bikeparks',
    regionsCount: 'Regionen',
    categoryCount: 'Merkmale',
    currentWeather: 'Aktuelles Wetter',
    averageTemperatures: 'Durchschnittstemperaturen',
    spring: 'Frühling',
    summer: 'Sommer',
    autumn: 'Herbst',
    winter: 'Winter',
    air: 'Luft',
    sea: 'Wasser',
    noData: 'Keine Daten',
    language: 'Sprache',
    generalInfo: 'Allgemeine Informationen',
    travelTourism: 'Bikeparks & Strecken',
    lifeWork: 'Anreise & Unterkunft',
    cultureFood: 'Infrastruktur & Service',
    practicalCautions: 'Sicherheitshinweise & Tipps',
    natureAndTrips: 'Strecken & Trails',
    historyAtmosphere: 'Infrastruktur und Atmosphäre',
    transportAndLife: 'Anreise und Unterkunft',
    backToOverview: 'Zurück zur Übersicht',
    backToHome: 'Zurück zur Startseite',
    backToCountry: 'Zurück zum Land',
    savedFavorite: 'In Favoriten gespeichert',
    addFavorite: 'Zu Favoriten hinzufügen',
  },
  fr: {
    home: 'Accueil',
    articlesAndGuides: 'Bike parks & pistes',
    countryArticles: 'Bike parks & trail centers',
    regionArticles: 'Bike parks dans cette région',
    regionCategories: 'Caractéristiques & filtres',
    featuredArticles: 'Bike parks recommandés',
    latestGuides: 'Derniers bike parks',
    latestArticles: 'Derniers bike parks',
    articleCategories: 'Caractéristiques & filtres',
    destinations: 'Pays & régions',
    destinationsIntro: 'Choisissez un pays et découvrez les meilleurs bike parks, remontées mécaniques, réseaux de pistes et conditions.',
    countries: 'Pays',
    exploreCountry: 'Explorer les bike parks du pays',
    regions: 'Régions',
    selectedRegions: 'Sélection de régions VTT',
    exploreRegion: 'Explorer les bike parks',
    noArticles: 'Aucun bike park pour le moment.',
    noCountryArticles: 'Aucun bike park répertorié pour ce pays pour le moment.',
    noRegionArticles: 'Aucun bike park pour cette région pour le moment.',
    noFilteredArticles: 'Aucun bike park ne correspond à ces critères.',
    loading: 'Chargement...',
    loadError: 'Les bike parks ne peuvent pas être chargés pour le moment.',
    readMore: 'Voir le bike park',
    travelGuide: 'Guide des bike parks',
    countryGuide: 'Bike parks dans le pays',
    regionGuide: 'Bike parks dans la région',
    planning: 'Préparation VTT',
    routes: 'Pistes & remontées',
    quickChoices: 'Choix rapides',
    filterArticles: 'Filtrer les bike parks',
    allCategories: 'Tous les parcs',
    allArticles: 'Tous les bike parks',
    showAllArticles: 'Voir tous les bike parks',
    showMoreArticles: 'Afficher plus',
    allArticlesIntro: 'Catalogue complet des bike parks et trail centers européens avec détails vérifiés sur les remontées, pistes et ateliers.',
    searchResults: 'Résultats de recherche',
    searchResultsFor: 'Résultats pour',
    articleSearchPlaceholder: 'Rechercher un bike park, trail center, lieu...',
    articleSearchButton: 'Rechercher',
    noSearchResults: 'Aucun bike park trouvé pour cette recherche.',
    allCountries: 'Tous les pays',
    showAllCountries: 'Voir tous les pays',
    allRegions: 'Toutes les régions',
    articlesCount: 'Bike parks',
    regionsCount: 'Régions',
    categoryCount: 'Caractéristiques',
    currentWeather: 'Météo actuelle',
    averageTemperatures: 'Températures moyennes',
    spring: 'Printemps',
    summer: 'Été',
    autumn: 'Automne',
    winter: 'Hiver',
    air: 'Air',
    sea: 'Eau',
    noData: 'Pas de données',
    language: 'Langue',
    generalInfo: 'Informations générales',
    travelTourism: 'Bike parks & pistes',
    lifeWork: 'Accès & hébergement',
    cultureFood: 'Services & équipement',
    practicalCautions: 'Conseils de sécurité pour riders',
    natureAndTrips: 'Pistes et sorties',
    historyAtmosphere: 'Infrastructures et ambiance',
    transportAndLife: 'Accès et séjour',
    backToOverview: 'Retour à l’aperçu',
    backToHome: 'Retour à l’accueil',
    backToCountry: 'Retour au pays',
    savedFavorite: 'Enregistré dans les favoris',
    addFavorite: 'Ajouter aux favoris',
  },
  es: {
    home: 'Inicio',
    articlesAndGuides: 'Bike parks y senderos',
    countryArticles: 'Bike parks y trail centers',
    regionArticles: 'Bike parks en esta región',
    regionCategories: 'Características y filtros',
    featuredArticles: 'Bike parks destacados',
    latestGuides: 'Últimos bike parks',
    latestArticles: 'Últimos bike parks',
    articleCategories: 'Características y filtros',
    destinations: 'Países y regiones',
    destinationsIntro: 'Elige un país y descubre los mejores bike parks, remontes, redes de pistas y condiciones de rodada.',
    countries: 'Países',
    exploreCountry: 'Explorar bike parks del país',
    regions: 'Regiones',
    selectedRegions: 'Regiones MTB seleccionadas',
    exploreRegion: 'Explorar bike parks',
    noArticles: 'Todavía no hay bike parks aquí.',
    noCountryArticles: 'Todavía no hay bike parks listados para este país.',
    noRegionArticles: 'Todavía no hay bike parks para esta región.',
    noFilteredArticles: 'Ningún bike park coincide con estos filtros.',
    loading: 'Cargando...',
    loadError: 'No se han podido cargar los bike parks ahora.',
    readMore: 'Ver bike park',
    travelGuide: 'Guía de bike parks',
    countryGuide: 'Bike parks en el país',
    regionGuide: 'Bike parks en la región',
    planning: 'Planificación MTB',
    routes: 'Pistas y remontes',
    quickChoices: 'Opciones rápidas',
    filterArticles: 'Filtrar bike parks',
    allCategories: 'Todos los parques',
    allArticles: 'Todos los bike parks',
    showAllArticles: 'Ver todos los bike parks',
    showMoreArticles: 'Mostrar más',
    allArticlesIntro: 'Catálogo completo de bike parks y trail centers europeos con datos verificados de remontes, pistas y servicios.',
    searchResults: 'Resultados de búsqueda',
    searchResultsFor: 'Resultados para',
    articleSearchPlaceholder: 'Buscar bike park, trail center, lugar...',
    articleSearchButton: 'Buscar',
    noSearchResults: 'No encontramos ningún bike park para esta búsqueda.',
    allCountries: 'Todos los países',
    showAllCountries: 'Ver todos los países',
    allRegions: 'Todas las regiones',
    articlesCount: 'Bike parks',
    regionsCount: 'Regiones',
    categoryCount: 'Características',
    currentWeather: 'Tiempo actual',
    averageTemperatures: 'Temperaturas medias',
    spring: 'Primavera',
    summer: 'Verano',
    autumn: 'Otoño',
    winter: 'Invierno',
    air: 'Aire',
    sea: 'Agua',
    noData: 'Sin datos',
    language: 'Idioma',
    generalInfo: 'Información general',
    travelTourism: 'Bike parks y senderos',
    lifeWork: 'Acceso y alojamiento',
    cultureFood: 'Servicios e instalaciones',
    practicalCautions: 'Seguridad y consejos para riders',
    natureAndTrips: 'Pistas y senderos',
    historyAtmosphere: 'Instalaciones y ambiente',
    transportAndLife: 'Transporte y alojamiento',
    backToOverview: 'Volver al resumen',
    backToHome: 'Volver al inicio',
    backToCountry: 'Volver al país',
    savedFavorite: 'Guardado en favoritos',
    addFavorite: 'Añadir a favoritos',
  },
};

export function getDestinationLabel(locale: string, key: string): string {
  const currentLocale = normalizeLocale(locale);
  return labels[currentLocale][key] ?? labels.cs[key] ?? key;
}
