import { normalizeLocale } from './articleLocalization';
import type { SupportedLocale } from './articleTypes';

type DestinationLabelMap = Record<SupportedLocale, Record<string, string>>;

const labels: DestinationLabelMap = {
  cs: {
    home: 'Domů',
    articlesAndGuides: 'Zajímavá místa',
    countryArticles: 'Tipy na výlet',
    regionArticles: 'Články v regionu',
    regionCategories: 'Témata v regionu',
    featuredArticles: 'Vybrané články',
    latestGuides: 'Nejnovější průvodce',
    latestArticles: 'Nejnovější články',
    articleCategories: 'Tematické kategorie',
    destinations: 'Destinace',
    destinationsIntro: 'Vyberte si zemi a projděte si regiony, praktické rady i aktuální články.',
    countries: 'Země',
    exploreCountry: 'Prozkoumat zemi',
    regions: 'Regiony a oblasti',
    selectedRegions: 'Výběr regionů',
    exploreRegion: 'Prozkoumat region',
    noArticles: 'Zatím zde nejsou žádné články.',
    noCountryArticles: 'V této zemi zatím nejsou žádné tipy na výlet.',
    noRegionArticles: 'V tomto regionu zatím nejsou žádné články.',
    noFilteredArticles: 'Pro tuto kombinaci zatím nejsou žádné články.',
    readMore: 'Číst dál',
    travelGuide: 'Cestovatelský průvodce',
    countryGuide: 'Průvodce zemí',
    regionGuide: 'Průvodce regionem',
    planning: 'Praktické plánování',
    routes: 'Regiony a trasy',
    quickChoices: 'Rychlé volby',
    filterArticles: 'Filtrovat články',
    allCategories: 'Všechny kategorie',
    allArticles: 'Všechny články',
    showAllArticles: 'Zobrazit všechny články',
    showMoreArticles: 'Zobrazit další',
    allArticlesIntro: 'Kompletní přehled cestovatelských článků, praktických míst a tipů napříč Evropou.',
    searchResults: 'Výsledky hledání',
    searchResultsFor: 'Výsledky hledání pro',
    articleSearchPlaceholder: 'Hledat v článcích',
    articleSearchButton: 'Hledat',
    noSearchResults: 'Pro tento dotaz jsme nenašli žádné články.',
    allCountries: 'Všechny země',
    showAllCountries: 'Zobrazit všechny země',
    allRegions: 'Všechny regiony',
    articlesCount: 'Článků',
    regionsCount: 'Regionů',
    categoryCount: 'Témat',
    currentWeather: 'Aktuální počasí',
    averageTemperatures: 'Průměrné teploty',
    spring: 'Jaro',
    summer: 'Léto',
    autumn: 'Podzim',
    winter: 'Zima',
    air: 'Vzduch',
    sea: 'Moře',
    noData: 'Bez dat',
    language: 'Jazyk',
    generalInfo: 'Obecné informace',
    travelTourism: 'Cestování',
    lifeWork: 'Život a práce',
    cultureFood: 'Kultura a jídlo',
    practicalCautions: 'Praktické rady',
    natureAndTrips: 'Výlety a příroda',
    historyAtmosphere: 'Gastronomie a atmosféra',
    transportAndLife: 'Doprava a pobyt',
    backToOverview: 'Zpět na přehled',
    backToHome: 'Zpět na hlavní stránku',
    backToCountry: 'Zpět na zemi',
    savedFavorite: 'Uloženo v oblíbených',
    addFavorite: 'Přidat do oblíbených',
  },
  en: {
    home: 'Home',
    articlesAndGuides: 'Places to visit',
    countryArticles: 'Trip ideas',
    regionArticles: 'Articles in this region',
    regionCategories: 'Topics in this region',
    featuredArticles: 'Featured articles',
    latestGuides: 'Latest guides',
    latestArticles: 'Latest articles',
    articleCategories: 'Thematic categories',
    destinations: 'Destinations',
    destinationsIntro: 'Choose a country and browse regions, practical tips, and current articles.',
    countries: 'Countries',
    exploreCountry: 'Explore country',
    regions: 'Regions and areas',
    selectedRegions: 'Selected regions',
    exploreRegion: 'Explore region',
    noArticles: 'No articles here yet.',
    noCountryArticles: 'There are no trip ideas for this country yet.',
    noRegionArticles: 'There are no articles for this region yet.',
    noFilteredArticles: 'No articles for this combination yet.',
    readMore: 'Read more',
    travelGuide: 'Travel guide',
    countryGuide: 'Country guide',
    regionGuide: 'Region guide',
    planning: 'Practical planning',
    routes: 'Regions and routes',
    quickChoices: 'Quick choices',
    filterArticles: 'Filter articles',
    allCategories: 'All categories',
    allArticles: 'All articles',
    showAllArticles: 'Show all articles',
    showMoreArticles: 'Show more',
    allArticlesIntro: 'A complete overview of travel articles, practical places, and tips across Europe.',
    searchResults: 'Search results',
    searchResultsFor: 'Search results for',
    articleSearchPlaceholder: 'Search articles',
    articleSearchButton: 'Search',
    noSearchResults: 'No articles found for this search.',
    allCountries: 'All countries',
    showAllCountries: 'Show all countries',
    allRegions: 'All regions',
    articlesCount: 'Articles',
    regionsCount: 'Regions',
    categoryCount: 'Topics',
    currentWeather: 'Current weather',
    averageTemperatures: 'Average temperatures',
    spring: 'Spring',
    summer: 'Summer',
    autumn: 'Autumn',
    winter: 'Winter',
    air: 'Air',
    sea: 'Sea',
    noData: 'No data',
    language: 'Language',
    generalInfo: 'General information',
    travelTourism: 'Travel',
    lifeWork: 'Life and work',
    cultureFood: 'Culture and food',
    practicalCautions: 'Practical notes',
    natureAndTrips: 'Trips and nature',
    historyAtmosphere: 'Food and atmosphere',
    transportAndLife: 'Transport and stay',
    backToOverview: 'Back to overview',
    backToHome: 'Back to homepage',
    backToCountry: 'Back to country',
    savedFavorite: 'Saved to favorites',
    addFavorite: 'Add to favorites',
  },
  de: {
    home: 'Start',
    articlesAndGuides: 'Sehenswerte Orte',
    countryArticles: 'Ausflugstipps',
    regionArticles: 'Artikel in dieser Region',
    regionCategories: 'Themen in dieser Region',
    featuredArticles: 'Ausgewählte Artikel',
    latestGuides: 'Neueste Reiseführer',
    latestArticles: 'Neueste Artikel',
    articleCategories: 'Thematische Kategorien',
    destinations: 'Reiseziele',
    destinationsIntro: 'Wähle ein Land und entdecke Regionen, praktische Tipps und aktuelle Artikel.',
    countries: 'Länder',
    exploreCountry: 'Land entdecken',
    regions: 'Regionen und Gebiete',
    selectedRegions: 'Ausgewählte Regionen',
    exploreRegion: 'Region entdecken',
    noArticles: 'Hier gibt es noch keine Artikel.',
    noCountryArticles: 'Für dieses Land gibt es noch keine Ausflugstipps.',
    noRegionArticles: 'Für diese Region gibt es noch keine Artikel.',
    noFilteredArticles: 'Für diese Kombination gibt es noch keine Artikel.',
    readMore: 'Weiterlesen',
    travelGuide: 'Reiseführer',
    countryGuide: 'Länderführer',
    regionGuide: 'Regionenführer',
    planning: 'Praktische Planung',
    routes: 'Regionen und Routen',
    quickChoices: 'Schnellauswahl',
    filterArticles: 'Artikel filtern',
    allCategories: 'Alle Kategorien',
    allArticles: 'Alle Artikel',
    showAllArticles: 'Alle Artikel anzeigen',
    showMoreArticles: 'Mehr anzeigen',
    allArticlesIntro: 'Eine komplette Übersicht praktischer Reiseartikel, Orte und Tipps in Europa.',
    searchResults: 'Suchergebnisse',
    searchResultsFor: 'Suchergebnisse für',
    articleSearchPlaceholder: 'Artikel suchen',
    articleSearchButton: 'Suchen',
    noSearchResults: 'Für diese Suche wurden keine Artikel gefunden.',
    allCountries: 'Alle Länder',
    showAllCountries: 'Alle Länder anzeigen',
    allRegions: 'Alle Regionen',
    articlesCount: 'Artikel',
    regionsCount: 'Regionen',
    categoryCount: 'Themen',
    currentWeather: 'Aktuelles Wetter',
    averageTemperatures: 'Durchschnittstemperaturen',
    spring: 'Frühling',
    summer: 'Sommer',
    autumn: 'Herbst',
    winter: 'Winter',
    air: 'Luft',
    sea: 'Meer',
    noData: 'Keine Daten',
    language: 'Sprache',
    generalInfo: 'Allgemeine Informationen',
    travelTourism: 'Reisen',
    lifeWork: 'Leben und Arbeiten',
    cultureFood: 'Kultur und Essen',
    practicalCautions: 'Praktische Hinweise',
    natureAndTrips: 'Ausflüge und Natur',
    historyAtmosphere: 'Essen und Atmosphäre',
    transportAndLife: 'Anreise und Aufenthalt',
    backToOverview: 'Zurück zur Übersicht',
    backToHome: 'Zurück zur Startseite',
    backToCountry: 'Zurück zum Land',
    savedFavorite: 'In Favoriten gespeichert',
    addFavorite: 'Zu Favoriten hinzufügen',
  },
  fr: {
    home: 'Accueil',
    articlesAndGuides: 'Lieux à voir',
    countryArticles: 'Idées de sorties',
    regionArticles: 'Articles dans cette région',
    regionCategories: 'Thèmes dans cette région',
    featuredArticles: 'Articles à la une',
    latestGuides: 'Derniers guides',
    latestArticles: 'Derniers articles',
    articleCategories: 'Catégories thématiques',
    destinations: 'Destinations',
    destinationsIntro: 'Choisissez un pays et explorez les régions, les conseils pratiques et les articles récents.',
    countries: 'Pays',
    exploreCountry: 'Explorer le pays',
    regions: 'Régions et zones',
    selectedRegions: 'Sélection de régions',
    exploreRegion: 'Explorer la région',
    noArticles: 'Aucun article pour le moment.',
    noCountryArticles: 'Aucune idée de sortie pour ce pays pour le moment.',
    noRegionArticles: 'Aucun article pour cette région pour le moment.',
    noFilteredArticles: 'Aucun article pour cette combinaison.',
    readMore: 'Lire la suite',
    travelGuide: 'Guide de voyage',
    countryGuide: 'Guide du pays',
    regionGuide: 'Guide régional',
    planning: 'Préparation pratique',
    routes: 'Régions et itinéraires',
    quickChoices: 'Choix rapides',
    filterArticles: 'Filtrer les articles',
    allCategories: 'Toutes les catégories',
    allArticles: 'Tous les articles',
    showAllArticles: 'Voir tous les articles',
    showMoreArticles: 'Afficher plus',
    allArticlesIntro: 'Tous les articles pratiques, lieux et conseils de voyage en Europe.',
    searchResults: 'Résultats de recherche',
    searchResultsFor: 'Résultats pour',
    articleSearchPlaceholder: 'Rechercher dans les articles',
    articleSearchButton: 'Rechercher',
    noSearchResults: 'Aucun article trouvé pour cette recherche.',
    allCountries: 'Tous les pays',
    showAllCountries: 'Voir tous les pays',
    allRegions: 'Toutes les régions',
    articlesCount: 'Articles',
    regionsCount: 'Régions',
    categoryCount: 'Thèmes',
    currentWeather: 'Météo actuelle',
    averageTemperatures: 'Températures moyennes',
    spring: 'Printemps',
    summer: 'Été',
    autumn: 'Automne',
    winter: 'Hiver',
    air: 'Air',
    sea: 'Mer',
    noData: 'Pas de données',
    language: 'Langue',
    generalInfo: 'Informations générales',
    travelTourism: 'Voyage',
    lifeWork: 'Vie et travail',
    cultureFood: 'Culture et cuisine',
    practicalCautions: 'Conseils pratiques',
    natureAndTrips: 'Sorties et nature',
    historyAtmosphere: 'Gastronomie et ambiance',
    transportAndLife: 'Accès et séjour',
    backToOverview: 'Retour à l’aperçu',
    backToHome: 'Retour à l’accueil',
    backToCountry: 'Retour au pays',
    savedFavorite: 'Enregistré dans les favoris',
    addFavorite: 'Ajouter aux favoris',
  },
  es: {
    home: 'Inicio',
    articlesAndGuides: 'Lugares que ver',
    countryArticles: 'Ideas para excursiones',
    regionArticles: 'Artículos en esta región',
    regionCategories: 'Temas de esta región',
    featuredArticles: 'Artículos destacados',
    latestGuides: 'Guías recientes',
    latestArticles: 'Artículos recientes',
    articleCategories: 'Categorías temáticas',
    destinations: 'Destinos',
    destinationsIntro: 'Elige un país y explora regiones, consejos prácticos y artículos actuales.',
    countries: 'Países',
    exploreCountry: 'Explorar país',
    regions: 'Regiones y zonas',
    selectedRegions: 'Selección de regiones',
    exploreRegion: 'Explorar región',
    noArticles: 'Todavía no hay artículos aquí.',
    noCountryArticles: 'Todavía no hay ideas para excursiones para este país.',
    noRegionArticles: 'Todavía no hay artículos para esta región.',
    noFilteredArticles: 'Todavía no hay artículos para esta combinación.',
    readMore: 'Leer más',
    travelGuide: 'Guía de viaje',
    countryGuide: 'Guía del país',
    regionGuide: 'Guía regional',
    planning: 'Planificación práctica',
    routes: 'Regiones y rutas',
    quickChoices: 'Opciones rápidas',
    filterArticles: 'Filtrar artículos',
    allCategories: 'Todas las categorías',
    allArticles: 'Todos los artículos',
    showAllArticles: 'Ver todos los artículos',
    showMoreArticles: 'Mostrar más',
    allArticlesIntro: 'Todos los artículos prácticos, lugares y consejos de viaje por Europa.',
    searchResults: 'Resultados de búsqueda',
    searchResultsFor: 'Resultados para',
    articleSearchPlaceholder: 'Buscar artículos',
    articleSearchButton: 'Buscar',
    noSearchResults: 'No encontramos artículos para esta búsqueda.',
    allCountries: 'Todos los países',
    showAllCountries: 'Ver todos los países',
    allRegions: 'Todas las regiones',
    articlesCount: 'Artículos',
    regionsCount: 'Regiones',
    categoryCount: 'Temas',
    currentWeather: 'Tiempo actual',
    averageTemperatures: 'Temperaturas medias',
    spring: 'Primavera',
    summer: 'Verano',
    autumn: 'Otoño',
    winter: 'Invierno',
    air: 'Aire',
    sea: 'Mar',
    noData: 'Sin datos',
    language: 'Idioma',
    generalInfo: 'Información general',
    travelTourism: 'Viajes',
    lifeWork: 'Vida y trabajo',
    cultureFood: 'Cultura y comida',
    practicalCautions: 'Consejos prácticos',
    natureAndTrips: 'Excursiones y naturaleza',
    historyAtmosphere: 'Gastronomía y ambiente',
    transportAndLife: 'Transporte y estancia',
    backToOverview: 'Volver al resumen',
    backToHome: 'Volver al inicio',
    backToCountry: 'Volver al país',
    savedFavorite: 'Guardado en favoritos',
    addFavorite: 'Añadir a favoritos',
  },
};

export function getDestinationLabel(locale: string, key: string): string {
  const currentLocale = normalizeLocale(locale);
  return labels[currentLocale][key] ?? labels.cs[key] ?? key;
}
